FROM centos:centos7.7.1908

ARG TZ
ARG servicePath=/etc/systemd/system/multi-user.target.wants
ARG serviceFile=/usr/lib/systemd/system/php54-php-fpm.service
ARG xdebugFile=/etc/opt/remi/php54/php.d/15-xdebug.ini

ARG PHP5_XDEBUG_REMOTE_ENABLE
ARG PHP5_XDEBUG_REMOTE_HOST
ARG PHP5_XDEBUG_REMOTE_PORT

RUN rpm -Uvh https://mirrors.ustc.edu.cn/epel/7/x86_64/Packages/e/epel-release-7-12.noarch.rpm \
&& rpm -Uvh https://mirrors.ustc.edu.cn/remi/enterprise/remi-release-7.rpm \
&& yum --enablerepo=remi,remi-php54 install -y php54-php-fpm php54-php-common php54-php-mysql php54-php-pear php54-php-gd php54-php-devel php54-php-mbstring php54-php-mcrypt php54-php-cli php54-php-pdo php54-php-redis php54-php-pecl-memcache php54-php-bcmath php54-php-xml php54-php-intl php54-php-imagick php54-php-xdebug php54-php-xhprof \
&& if [[ ! -d "${servicePath}" ]]; then \
     echo "mkdir -p ${servicePath}..."; \
     mkdir -p "${servicePath}"; \
   fi \
&& if [[ -e "${serviceFile}" ]]; then \
     echo "ln -sf ${serviceFile} ${servicePath}/nginx.service..."; \
     ln -sf ${serviceFile} ${servicePath}/php54-php-fpm.service; \
   fi \
&& if [[ -e "${xdebugFile}" ]]; then \
     echo -e "xdebug.remote_enable = ${PHP7_XDEBUG_REMOTE_ENABLE}\nxdebug.remote_host = ${PHP7_XDEBUG_REMOTE_HOST}\nxdebug.remote_port = 9090" >> ${xdebugFile}; \
     ln -sf ${serviceFile} ${servicePath}/php54-php-fpm.service; \
   fi \
&& ln -sf /opt/remi/php54/root/usr/bin/php /usr/bin/php \
&& ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
&& ln -sf /usr/lib/systemd/system/php54-php-fpm.service /usr/lib/systemd/system/php-fpm.service \
&& export TZ="${TZ}"

EXPOSE 9000 9090

CMD ["/usr/sbin/init"]